package:
  name: python-cgrid
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_0
  script:
    - export CXXFLAGS="${CXXFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"  # [osx]
    - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"  # [osx]
    - python setup.py build_ext -I {{ PREFIX }}/include
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - cython >=0.28.0
    - setuptools
    - numpy >=1.0
    - cgrid =={{ PROJECT_VERSION }}
    - cellcutoff 0.2.*
  run:
    - cgrid
    - cellcutoff 0.2.*
    - python-cellcutoff 0.2.*
    - python
    - numpy

test:
  requires:
    - pytest >=4.2.0
    - pytest-xdist
  commands:
    - conda inspect linkages python-cgrid
    - pytest --pyargs cgrid -v -n auto

about:
  description: A library for for molecular numerical integration.
  home: https://github.com/theochem/cgrid
  license: GPL3
  license_file: LICENSE.txt
  summary: CGrid is a library for for molecular numerical integration.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
