package:
  name: qcgrids
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  string: 0

requirements:
  build:
    - cmake
    - {{ compiler("cxx") }}
    - cellcutoff
  run:
    - cellcutoff

about:
  description: A numerical integration library for quantum chemistry
  home: https://github.com/theochem/qcgrids
  license: GPL3
  license_file: LICENSE.txt
  summary: QCGrids is a numerical integration library for quantum chemistry.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
