package:
  name: python-qcgrids
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
   - BUILD_TYPE
  number: 0
  string: py{{ CONDA_PY }}_0
  script:
   - if [[ ${BUILD_TYPE} == "debug" ]]; then
       python setup.py build --define CYTHON_TRACE_NOGIL;
     fi;
     python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython >=0.24.1
    - cellcutoff
    - python-cellcutoff
    - qcgrids
    - setuptools
    - nose
    - gcc
  run:
    - cellcutoff
    - python-cellcutoff
    - qcgrids
    - python
    - numpy
    - nose
    - libgcc

about:
  description: A numerical integration library for quantum chemistry
  home: https://github.com/theochem/qcgrids
  license: GPL3
  license_file: LICENSE.txt
  summary: QCGrids is a numerical integration library for quantum chemistry.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
