package:
  name: python-qcgrids
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  string: py{{ CONDA_PY }}_0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython >=0.24.1
    - cellcutoff
    - python-cellcutoff
    - qcgrids
    - setuptools
    - nose
    - {{ compiler("cxx") }}
    - {{ compiler("c") }}
  run:
    - cellcutoff
    - python-cellcutoff
    - qcgrids
    - python
    - numpy
    - nose

about:
  description: A numerical integration library for quantum chemistry
  home: https://github.com/theochem/qcgrids
  license: GPL3
  license_file: LICENSE.txt
  summary: QCGrids is a numerical integration library for quantum chemistry.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
